---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by sejolyn.
--- DateTime: 2026/1/22 23:52
--- 判断库存是否充足 && 用户是否重复抢购 && 库存扣减 && 订单信息写入队列
-- 优惠卷ID
local voucherId = ARGV[1]
-- 用户ID
local userId = ARGV[2]
-- 订单ID
local orderId = ARGV[3]

-- 库存key
local stockKey = 'seckill:stock:' .. voucherId
-- 订单key
local orderKey = 'seckill:order:' .. voucherId

-- 1. 判断库存是否充足
if (tonumber(redis.call('get', stockKey)) <= 0) then
    -- 库存不足
    return 1
end

-- 2. 判断用户是否重复抢购
if (redis.call('sismember', orderKey, userId) == 1) then
    -- 用户已抢购过
    return 2
end

-- 3. 扣减库存
redis.call('incrby', stockKey, -1)
-- 4. 记录用户抢购信息
redis.call('sadd', orderKey, userId)
-- 5. 发送消息到队列中
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)

return 0